/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reproductormusica;

import java.io.File;
import javax.swing.JFrame;

/**
 *
 * @author PC
 */
public class interfazReproductor extends javax.swing.JFrame {
    /**
     * Creates new form interfazReproductor
     */
    String rutaCancion1 = new File("").getAbsolutePath()+"\\src\\songs\\505ArticMonkeys.mp3";
    String rutaPortadaCancion1 = new File("").getAbsolutePath()+"\\src\\images\\portada505.png";
    Cancion cancion1 = new Cancion("505", "Artic Monkeys",rutaCancion1, rutaPortadaCancion1);
    
    public interfazReproductor() {
        initComponents();
        setLocationRelativeTo(null);
        cambiarCancionUI(cancion1);
    }
    
    public void cambiarCancionUI(Cancion cancion){
        songTitle.setText(cancion.getTitulo());
        songAuthor.setText(cancion.getAutor());
        songIcon.setIcon(cancion.getImagenPortada());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        songPanel = new javax.swing.JPanel();
        songTitle = new javax.swing.JLabel();
        songAuthor = new javax.swing.JLabel();
        songIcon = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        nextSongButton = new javax.swing.JButton();
        previousSongButton = new javax.swing.JButton();
        SongPanelBackgound = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("© 2024 PityFy By Jorge. All Rights Reserved.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 660, 300, 14);

        songPanel.setBackground(new java.awt.Color(51, 51, 51));
        songPanel.setOpaque(false);
        songPanel.setLayout(null);

        songTitle.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        songTitle.setForeground(new java.awt.Color(204, 204, 204));
        songTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        songTitle.setText("tituloCancion");
        songPanel.add(songTitle);
        songTitle.setBounds(80, 340, 480, 50);

        songAuthor.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        songAuthor.setForeground(new java.awt.Color(153, 153, 153));
        songAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        songAuthor.setText("Autor/ Autores");
        songPanel.add(songAuthor);
        songAuthor.setBounds(80, 375, 480, 40);

        songIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        songPanel.add(songIcon);
        songIcon.setBounds(145, 30, 340, 300);

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playIcon.png"))); // NOI18N
        playButton.setBorder(null);
        playButton.setBorderPainted(false);
        playButton.setContentAreaFilled(false);
        playButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        songPanel.add(playButton);
        playButton.setBounds(265, 420, 110, 110);

        nextSongButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/siguienteIcon.png"))); // NOI18N
        nextSongButton.setBorder(null);
        nextSongButton.setBorderPainted(false);
        nextSongButton.setContentAreaFilled(false);
        nextSongButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextSongButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        songPanel.add(nextSongButton);
        nextSongButton.setBounds(390, 440, 80, 70);

        previousSongButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anteriorIcon.png"))); // NOI18N
        previousSongButton.setBorder(null);
        previousSongButton.setBorderPainted(false);
        previousSongButton.setContentAreaFilled(false);
        previousSongButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousSongButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        songPanel.add(previousSongButton);
        previousSongButton.setBounds(170, 440, 80, 70);

        SongPanelBackgound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SongPanelBackgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoReproductorMusicaBlurred.png"))); // NOI18N
        SongPanelBackgound.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        songPanel.add(SongPanelBackgound);
        SongPanelBackgound.setBounds(0, 0, 630, 580);

        getContentPane().add(songPanel);
        songPanel.setBounds(230, 50, 630, 580);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoReproductorMusica.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(-3, -4, 1090, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazReproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazReproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazReproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazReproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazReproductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SongPanelBackgound;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextSongButton;
    private javax.swing.JButton playButton;
    private javax.swing.JButton previousSongButton;
    private javax.swing.JLabel songAuthor;
    private javax.swing.JLabel songIcon;
    private javax.swing.JPanel songPanel;
    private javax.swing.JLabel songTitle;
    // End of variables declaration//GEN-END:variables
}
