/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reproductormusica;

import java.awt.Color;
import java.io.File;
import java.util.ArrayList;

import javax.swing.ImageIcon;


/**
 *
 * @author PC
 */
public class interfazReproductor extends javax.swing.JFrame {

    //IMPORTAR CANCIONES
    String[][] cancionesData = {
        {"505", "Arctic Monkeys", "songs\\505ArticMonkeys.mp3", "images\\portada505.png"},
        {"Wake Me Up When September Ends", "Green Day", "songs\\WakeMeUpWhenSeptemberEnds_GreenDay.mp3", "images\\wakeMeUpWhenSeptemberEndsCover.png"},
        {"Apple", "Charli XCX", "songs\\Apple_CharliXCX.mp3", "images\\AppleCover.png"},
        {"Niégame Tres Veces", "Silvestre Dangond", "songs\\NiegameTresVeces_SilvestreDangond.mp3", "images\\niegameTresVecesCover.jpeg"},
        {"Nobody", "Mitski", "songs\\nobody_Mitski.mp3", "images\\nobodyCover.jpeg"},
        {"Feather", "Sabrina Carpenter", "songs\\Feather_SabrinaCarpenter.mp3", "images\\FeatherCover.jpeg"},
        {"Otonoke", "Creepy Nuts", "songs\\Otonoke_CreepyNuts.mp3", "images\\OtonokeCover.jpeg"},
        {"El Ritmo Que Nos Une", "Ryan Castro", "songs\\ElRitmoQueNosUne_RyanCastro.mp3", "images\\elRitmoquenosuneCover.jpeg"}
    };

    //Importar icono de pausa y play
    ImageIcon iconoPausa = new ImageIcon(new File("").getAbsolutePath() + "\\src\\images\\stopIcon.png");
    ImageIcon iconoPlay = new ImageIcon(new File("").getAbsolutePath() + "\\src\\images\\playIcon.png");

    //Objeto de ListaCircular
    ListaCircular playList = new ListaCircular();

    //Iterador Primer Click cancion
    Boolean isPlaying = false;
    Boolean firstClickSong = true;

    public interfazReproductor() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon icono = new ImageIcon(getClass().getResource("/images/espotifai.png"));
        setIconImage(icono.getImage());
        reproductionButton.setIcon(iconoPlay);
        reproductionButton.requestFocusInWindow();
        //Agregar canciones a la playlist.
        for (String[] datos : cancionesData) {
            String titulo = datos[0];
            String artista = datos[1];
            String rutaCancion = new File("").getAbsolutePath() + "\\src\\" + datos[2];
            String rutaPortada = new File("").getAbsolutePath() + "\\src\\" + datos[3];

            Cancion cancion = new Cancion(titulo, artista, rutaCancion, rutaPortada);
            playList.agregar(cancion);
        }
        cambiarCancionUI(playList.getActual().getCancion());
    }

    public void cambiarCancionUI(Cancion cancion) {
        songTitle.setText(cancion.getTitulo());
        songAuthor.setText(cancion.getAutor());
        songIcon.setIcon(cancion.getImagenPortada());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogo = new javax.swing.JDialog();
        panelDialogo = new javax.swing.JPanel();
        txtCancionBuscada = new javax.swing.JLabel();
        TextoAdvertencia = new javax.swing.JLabel();
        TextoAdvertencia2 = new javax.swing.JLabel();
        SongPanelBackgound1 = new javax.swing.JLabel();
        espotifai = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        songPanel = new javax.swing.JPanel();
        songTitle = new javax.swing.JLabel();
        songAuthor = new javax.swing.JLabel();
        iconSongPanel = new javax.swing.JPanel();
        songIcon = new javax.swing.JLabel();
        reproductionButton = new javax.swing.JButton();
        nextSongButton = new javax.swing.JButton();
        previousSongButton = new javax.swing.JButton();
        SongPanelBackgound = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        dialogo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogo.setBackground(new java.awt.Color(153, 0, 51));
        dialogo.setResizable(false);
        dialogo.setSize(new java.awt.Dimension(600, 300));
        dialogo.getContentPane().setLayout(null);

        panelDialogo.setLayout(null);

        txtCancionBuscada.setFont(new java.awt.Font("Cascadia Mono", 0, 22)); // NOI18N
        txtCancionBuscada.setForeground(new java.awt.Color(204, 204, 204));
        txtCancionBuscada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelDialogo.add(txtCancionBuscada);
        txtCancionBuscada.setBounds(160, 130, 280, 40);

        TextoAdvertencia.setFont(new java.awt.Font("Cascadia Mono", 1, 22)); // NOI18N
        TextoAdvertencia.setForeground(new java.awt.Color(255, 255, 255));
        TextoAdvertencia.setText("No se han encontrado resultados para:");
        panelDialogo.add(TextoAdvertencia);
        TextoAdvertencia.setBounds(50, 70, 510, 50);

        TextoAdvertencia2.setBackground(new java.awt.Color(51, 51, 51));
        TextoAdvertencia2.setFont(new java.awt.Font("Cascadia Mono", 0, 16)); // NOI18N
        TextoAdvertencia2.setForeground(new java.awt.Color(204, 204, 204));
        TextoAdvertencia2.setText("Asegurate de escribir bien el nombre de la cancion.");
        panelDialogo.add(TextoAdvertencia2);
        TextoAdvertencia2.setBounds(70, 180, 460, 50);

        SongPanelBackgound1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SongPanelBackgound1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoReproductorMusicaBlurred.png"))); // NOI18N
        SongPanelBackgound1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        panelDialogo.add(SongPanelBackgound1);
        SongPanelBackgound1.setBounds(0, 0, 600, 300);

        dialogo.getContentPane().add(panelDialogo);
        panelDialogo.setBounds(0, 0, 600, 300);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MusiKPlayer");
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        espotifai.setFont(new java.awt.Font("Cascadia Mono", 0, 11)); // NOI18N
        espotifai.setForeground(new java.awt.Color(255, 255, 255));
        espotifai.setText("© 2024 MusiKPlayer By Jorge.");
        getContentPane().add(espotifai);
        espotifai.setBounds(10, 660, 300, 14);

        searchPanel.setBackground(new java.awt.Color(51, 51, 51));
        searchPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 40, true));
        searchPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        searchPanel.setOpaque(false);
        searchPanel.setLayout(null);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscarIcon.png"))); // NOI18N
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        searchPanel.add(btnBuscar);
        btnBuscar.setBounds(5, 2, 40, 30);

        txtSearch.setBackground(new java.awt.Color(51, 51, 51));
        txtSearch.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(102, 102, 102));
        txtSearch.setText("¿Que quieres escuchar hoy?");
        txtSearch.setBorder(null);
        txtSearch.setCaretColor(new java.awt.Color(255, 255, 255));
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSearchMouseExited(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });
        searchPanel.add(txtSearch);
        txtSearch.setBounds(45, 0, 230, 35);

        getContentPane().add(searchPanel);
        searchPanel.setBounds(410, 40, 280, 35);

        songPanel.setBackground(new java.awt.Color(51, 51, 51));
        songPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 40, true));
        songPanel.setLayout(null);

        songTitle.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        songTitle.setForeground(new java.awt.Color(204, 204, 204));
        songTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        songTitle.setText("tituloCancion");
        songPanel.add(songTitle);
        songTitle.setBounds(80, 330, 480, 50);

        songAuthor.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        songAuthor.setForeground(new java.awt.Color(153, 153, 153));
        songAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        songAuthor.setText("Autor/ Autores");
        songPanel.add(songAuthor);
        songAuthor.setBounds(80, 365, 480, 40);

        iconSongPanel.setBackground(new java.awt.Color(102, 51, 255));
        iconSongPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        iconSongPanel.setOpaque(false);
        iconSongPanel.setLayout(null);
        songPanel.add(iconSongPanel);
        iconSongPanel.setBounds(170, 30, 300, 300);

        songIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        songPanel.add(songIcon);
        songIcon.setBounds(150, 30, 340, 300);

        reproductionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playIcon.png"))); // NOI18N
        reproductionButton.setBorder(null);
        reproductionButton.setBorderPainted(false);
        reproductionButton.setContentAreaFilled(false);
        reproductionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reproductionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproductionButtonActionPerformed(evt);
            }
        });
        reproductionButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reproductionButtonKeyPressed(evt);
            }
        });
        songPanel.add(reproductionButton);
        reproductionButton.setBounds(292, 422, 60, 60);

        nextSongButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/siguienteIcon.png"))); // NOI18N
        nextSongButton.setBorder(null);
        nextSongButton.setBorderPainted(false);
        nextSongButton.setContentAreaFilled(false);
        nextSongButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextSongButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextSongButton.setRequestFocusEnabled(false);
        nextSongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextSongButtonActionPerformed(evt);
            }
        });
        songPanel.add(nextSongButton);
        nextSongButton.setBounds(370, 430, 40, 40);

        previousSongButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anteriorIcon.png"))); // NOI18N
        previousSongButton.setBorder(null);
        previousSongButton.setBorderPainted(false);
        previousSongButton.setContentAreaFilled(false);
        previousSongButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousSongButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previousSongButton.setRequestFocusEnabled(false);
        previousSongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousSongButtonActionPerformed(evt);
            }
        });
        songPanel.add(previousSongButton);
        previousSongButton.setBounds(230, 430, 40, 40);

        SongPanelBackgound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SongPanelBackgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoReproductorMusicaBlurred.png"))); // NOI18N
        SongPanelBackgound.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        songPanel.add(SongPanelBackgound);
        SongPanelBackgound.setBounds(0, 0, 630, 540);

        getContentPane().add(songPanel);
        songPanel.setBounds(230, 90, 630, 540);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoReproductorMusica.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(-3, -4, 1090, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reproductionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproductionButtonActionPerformed
        if (firstClickSong) {
            playList.reproducir(playList.getActual().getCancion().getRutaCancion());
            reproductionButton.setIcon(iconoPausa);
            firstClickSong = false;
            isPlaying = true;
        } else {
            if (isPlaying) {
                playList.pausar();
                isPlaying = false;
                reproductionButton.setIcon(iconoPlay);
            } else {
                playList.reanudar(playList.getActual().getCancion().getRutaCancion());
                reproductionButton.setIcon(iconoPausa);
                isPlaying = true;
            }
        }

    }//GEN-LAST:event_reproductionButtonActionPerformed

    private void nextSongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextSongButtonActionPerformed
        firstClickSong = true;
        playList.cerrarCancion(playList.getActual().getCancion().getRutaCancion());
        playList.avanzar();
        cambiarCancionUI(playList.getActual().getCancion());
        reproductionButton.setIcon(iconoPlay);
        reproductionButton.doClick();
    }//GEN-LAST:event_nextSongButtonActionPerformed

    private void previousSongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousSongButtonActionPerformed
        firstClickSong = true;
        playList.cerrarCancion(playList.getActual().getCancion().getRutaCancion());
        playList.retroceder();
        cambiarCancionUI(playList.getActual().getCancion());
        reproductionButton.setIcon(iconoPlay);
        reproductionButton.doClick();
    }//GEN-LAST:event_previousSongButtonActionPerformed

    private void reproductionButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reproductionButtonKeyPressed

    }//GEN-LAST:event_reproductionButtonKeyPressed

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        txtSearch.setText("");
        txtSearch.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        txtSearch.setText("¿Que quieres escuchar hoy?");
        txtSearch.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_txtSearchFocusLost

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnBuscar.doClick();
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void txtSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseExited
        reproductionButton.requestFocus();
    }//GEN-LAST:event_txtSearchMouseExited

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String cancionBuscada = txtSearch.getText();
        NodoCancion nodoCancionSearch = playList.buscarCancion(cancionBuscada);
        if (nodoCancionSearch != null) {
            firstClickSong = true;
            isPlaying = false;
            playList.cerrarCancion(playList.getActual().getCancion().getRutaCancion());
            reproductionButton.doClick();
            Cancion cancionEncontrada = nodoCancionSearch.getCancion();
            playList.setActual(nodoCancionSearch);
            cambiarCancionUI(cancionEncontrada);
        } else {
            txtCancionBuscada.setText(cancionBuscada);
            dialogo.setLocationRelativeTo(null);
            dialogo.setVisible(true);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazReproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazReproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazReproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazReproductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazReproductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SongPanelBackgound;
    private javax.swing.JLabel SongPanelBackgound1;
    private javax.swing.JLabel TextoAdvertencia;
    private javax.swing.JLabel TextoAdvertencia2;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JDialog dialogo;
    private javax.swing.JLabel espotifai;
    private javax.swing.JPanel iconSongPanel;
    private javax.swing.JButton nextSongButton;
    private javax.swing.JPanel panelDialogo;
    private javax.swing.JButton previousSongButton;
    private javax.swing.JButton reproductionButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel songAuthor;
    private javax.swing.JLabel songIcon;
    private javax.swing.JPanel songPanel;
    private javax.swing.JLabel songTitle;
    private javax.swing.JLabel txtCancionBuscada;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
